/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5654
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.api

import com.patagona.pricemonitor.client.model.GetPriceRecommendationApiResponse
import com.patagona.pricemonitor.client.model.GetPriceRecommendationsResponse
import java.time.OffsetDateTime
import com.patagona.pricemonitor.client.model.PriceRecommendationApiQueryV2
import com.patagona.pricemonitor.client.model.QueryPriceRecommendationsV2ApiResponse
import com.patagona.pricemonitor.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object PricerecommendationsApi {

  def apply(baseUrl: String = "https://api.patagona.de")(implicit serializer: SttpSerializer) = new PricerecommendationsApi(baseUrl)
}

class PricerecommendationsApi(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   */
  def deleteRepricingStrategyVendorV2(contractId: String)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/api/2/v/contracts/${contractId}/settings/repricingstrategy")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : GetPriceRecommendationApiResponse (A paginated list of price recommendations is returned for the specified timerange. Only the newest price recommendations are returned in case of multiple price recommendations per product.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param startTime Timestamp of start of time range, formatted as ISO Date (i.e. 2018-04-06T13:46:13Z) in UTC
   * @param endTime Timestamp of end of time range, formatted as ISO Date (i.e. 2018-04-06T13:46:13Z) in UTC
   * @param start Start price-recommendation index for pagination
   * @param limit Number of price-recommendations for pagination
   */
  def getPriceRecommendation(contractId: String, startTime: OffsetDateTime, endTime: OffsetDateTime, start: Int, limit: Option[Int] = None)(implicit basicAuth: BasicCredentials): ApiRequestT[GetPriceRecommendationApiResponse] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/2/v/contracts/${contractId}/result/pricerecommendations?startTime=$startTime&endTime=$endTime&start=$start&limit=$limit")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[GetPriceRecommendationApiResponse])

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param startTime 
   * @param endTime 
   * @param maxPositions 
   */
  def getPriceRecommendationStatsVendorV2(contractId: String, startTime: OffsetDateTime, endTime: OffsetDateTime, maxPositions: Int)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/2/v/contracts/${contractId}/result/pricerecommendationstats?startTime=$startTime&endTime=$endTime&maxPositions=$maxPositions")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : GetPriceRecommendationsResponse (No response was specified)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param start Where to start fetching the recommendations
   * @param limit Maximal number of results
   * @param since Timestamp of the oldest results
   */
  def getPriceRecommendations(contractId: String, start: Option[Int] = None, limit: Option[Int] = None, since: Option[OffsetDateTime] = None)(implicit basicAuth: BasicCredentials): ApiRequestT[GetPriceRecommendationsResponse] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/1/${contractId}/products/analysis/pricerecommendations?start=$start&limit=$limit&since=$since")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[GetPriceRecommendationsResponse])

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   */
  def getRepricingStrategyVendorV2(contractId: String)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/2/v/contracts/${contractId}/settings/repricingstrategy")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param portal 
   * @param until 
   */
  def getStats(contractId: String, portal: String, until: Option[OffsetDateTime] = None)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/1/${contractId}/products/analysis/pricerecommendations/stats/${portal}?until=$until")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId 
   */
  def getTimeStamps(contractId: Long)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/api/1/${contractId}/products/analysis/timestamps")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : Any (This is a generated entry and needs to be described.)
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param body This is a generated entry and needs to be described.
   */
  def putRepricingStrategyVendorV2(contractId: String, body: Option[Any] = None)(implicit basicAuth: BasicCredentials): ApiRequestT[Any] =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/api/2/v/contracts/${contractId}/settings/repricingstrategy")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .body(body)
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : QueryPriceRecommendationsV2ApiResponse (A paginated list of price recommendations is returned for the specified timerange. <br> Only the newest price recommendations are returned in case of multiple price recommendations per product. )
   * 
   * Available security schemes:
   *   BasicAuth (http)
   * 
   * @param contractId ID of the contract
   * @param priceRecommendationApiQueryV2 The request body specifies which price recommendations will be searched for.
   */
  def queryPriceRecommendationsVendorV2(contractId: String, priceRecommendationApiQueryV2: Option[PriceRecommendationApiQueryV2] = None)(implicit basicAuth: BasicCredentials): ApiRequestT[QueryPriceRecommendationsV2ApiResponse] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/api/2/v/contracts/${contractId}/result/pricerecommendations/query")
      .contentType("application/json")
      .auth.basic(basicAuth.user, basicAuth.password)
      .body(priceRecommendationApiQueryV2)
      .response(asJson[QueryPriceRecommendationsV2ApiResponse])

}

