# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6674
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pricemonitor_api_client.configuration import Configuration


class ApiContract(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active': 'bool',
        'company_name': 'str',
        'contract_id': 'str',
        'contract_name': 'str',
        'contract_type': 'str',
        'expiration_date': 'datetime'
    }

    attribute_map = {
        'active': 'active',
        'company_name': 'companyName',
        'contract_id': 'contractId',
        'contract_name': 'contractName',
        'contract_type': 'contractType',
        'expiration_date': 'expirationDate'
    }

    def __init__(self, active=None, company_name=None, contract_id=None, contract_name=None, contract_type=None, expiration_date=None, local_vars_configuration=None):  # noqa: E501
        """ApiContract - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._active = None
        self._company_name = None
        self._contract_id = None
        self._contract_name = None
        self._contract_type = None
        self._expiration_date = None
        self.discriminator = None

        if active is not None:
            self.active = active
        if company_name is not None:
            self.company_name = company_name
        if contract_id is not None:
            self.contract_id = contract_id
        if contract_name is not None:
            self.contract_name = contract_name
        if contract_type is not None:
            self.contract_type = contract_type
        if expiration_date is not None:
            self.expiration_date = expiration_date

    @property
    def active(self):
        """Gets the active of this ApiContract.  # noqa: E501


        :return: The active of this ApiContract.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ApiContract.


        :param active: The active of this ApiContract.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def company_name(self):
        """Gets the company_name of this ApiContract.  # noqa: E501


        :return: The company_name of this ApiContract.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this ApiContract.


        :param company_name: The company_name of this ApiContract.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def contract_id(self):
        """Gets the contract_id of this ApiContract.  # noqa: E501


        :return: The contract_id of this ApiContract.  # noqa: E501
        :rtype: str
        """
        return self._contract_id

    @contract_id.setter
    def contract_id(self, contract_id):
        """Sets the contract_id of this ApiContract.


        :param contract_id: The contract_id of this ApiContract.  # noqa: E501
        :type: str
        """

        self._contract_id = contract_id

    @property
    def contract_name(self):
        """Gets the contract_name of this ApiContract.  # noqa: E501


        :return: The contract_name of this ApiContract.  # noqa: E501
        :rtype: str
        """
        return self._contract_name

    @contract_name.setter
    def contract_name(self, contract_name):
        """Sets the contract_name of this ApiContract.


        :param contract_name: The contract_name of this ApiContract.  # noqa: E501
        :type: str
        """

        self._contract_name = contract_name

    @property
    def contract_type(self):
        """Gets the contract_type of this ApiContract.  # noqa: E501


        :return: The contract_type of this ApiContract.  # noqa: E501
        :rtype: str
        """
        return self._contract_type

    @contract_type.setter
    def contract_type(self, contract_type):
        """Sets the contract_type of this ApiContract.


        :param contract_type: The contract_type of this ApiContract.  # noqa: E501
        :type: str
        """

        self._contract_type = contract_type

    @property
    def expiration_date(self):
        """Gets the expiration_date of this ApiContract.  # noqa: E501


        :return: The expiration_date of this ApiContract.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this ApiContract.


        :param expiration_date: The expiration_date of this ApiContract.  # noqa: E501
        :type: datetime
        """

        self._expiration_date = expiration_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiContract):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiContract):
            return True

        return self.to_dict() != other.to_dict()
