# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6775
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pricemonitor_api_client.configuration import Configuration


class ComPatagonaPricemonitorShareApiOneOfProductsQuery(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'one_of': 'ComPatagonaPricemonitorShareApiProductIdQuery'
    }

    attribute_map = {
        'one_of': 'oneOf'
    }

    def __init__(self, one_of=None, local_vars_configuration=None):  # noqa: E501
        """ComPatagonaPricemonitorShareApiOneOfProductsQuery - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._one_of = None
        self.discriminator = None

        self.one_of = one_of

    @property
    def one_of(self):
        """Gets the one_of of this ComPatagonaPricemonitorShareApiOneOfProductsQuery.  # noqa: E501


        :return: The one_of of this ComPatagonaPricemonitorShareApiOneOfProductsQuery.  # noqa: E501
        :rtype: ComPatagonaPricemonitorShareApiProductIdQuery
        """
        return self._one_of

    @one_of.setter
    def one_of(self, one_of):
        """Sets the one_of of this ComPatagonaPricemonitorShareApiOneOfProductsQuery.


        :param one_of: The one_of of this ComPatagonaPricemonitorShareApiOneOfProductsQuery.  # noqa: E501
        :type: ComPatagonaPricemonitorShareApiProductIdQuery
        """
        if self.local_vars_configuration.client_side_validation and one_of is None:  # noqa: E501
            raise ValueError("Invalid value for `one_of`, must not be `None`")  # noqa: E501

        self._one_of = one_of

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComPatagonaPricemonitorShareApiOneOfProductsQuery):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComPatagonaPricemonitorShareApiOneOfProductsQuery):
            return True

        return self.to_dict() != other.to_dict()
