# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.5818
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pricemonitor_api_client.configuration import Configuration


class GenericTaskWithUrl(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'creation_date': 'datetime',
        'start_date': 'datetime',
        'finish_date': 'datetime',
        'state': 'str',
        'failures': 'list[object]',
        'task_id': 'str',
        'parent_id': 'str',
        'task_type': 'str',
        'data': 'object',
        'result': 'object',
        'failure_code': 'str',
        'url': 'str'
    }

    attribute_map = {
        'creation_date': 'creationDate',
        'start_date': 'startDate',
        'finish_date': 'finishDate',
        'state': 'state',
        'failures': 'failures',
        'task_id': 'taskId',
        'parent_id': 'parentId',
        'task_type': 'taskType',
        'data': 'data',
        'result': 'result',
        'failure_code': 'failureCode',
        'url': 'url'
    }

    def __init__(self, creation_date=None, start_date=None, finish_date=None, state=None, failures=None, task_id=None, parent_id=None, task_type=None, data=None, result=None, failure_code=None, url=None, local_vars_configuration=None):  # noqa: E501
        """GenericTaskWithUrl - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._creation_date = None
        self._start_date = None
        self._finish_date = None
        self._state = None
        self._failures = None
        self._task_id = None
        self._parent_id = None
        self._task_type = None
        self._data = None
        self._result = None
        self._failure_code = None
        self._url = None
        self.discriminator = None

        self.creation_date = creation_date
        if start_date is not None:
            self.start_date = start_date
        if finish_date is not None:
            self.finish_date = finish_date
        self.state = state
        if failures is not None:
            self.failures = failures
        self.task_id = task_id
        if parent_id is not None:
            self.parent_id = parent_id
        self.task_type = task_type
        if data is not None:
            self.data = data
        if result is not None:
            self.result = result
        if failure_code is not None:
            self.failure_code = failure_code
        self.url = url

    @property
    def creation_date(self):
        """Gets the creation_date of this GenericTaskWithUrl.  # noqa: E501

        The creation date of this task  # noqa: E501

        :return: The creation_date of this GenericTaskWithUrl.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this GenericTaskWithUrl.

        The creation date of this task  # noqa: E501

        :param creation_date: The creation_date of this GenericTaskWithUrl.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and creation_date is None:  # noqa: E501
            raise ValueError("Invalid value for `creation_date`, must not be `None`")  # noqa: E501

        self._creation_date = creation_date

    @property
    def start_date(self):
        """Gets the start_date of this GenericTaskWithUrl.  # noqa: E501

        The timestamp of when processing of this task was started  # noqa: E501

        :return: The start_date of this GenericTaskWithUrl.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this GenericTaskWithUrl.

        The timestamp of when processing of this task was started  # noqa: E501

        :param start_date: The start_date of this GenericTaskWithUrl.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def finish_date(self):
        """Gets the finish_date of this GenericTaskWithUrl.  # noqa: E501

        The timestamp of when processing of this task finished  # noqa: E501

        :return: The finish_date of this GenericTaskWithUrl.  # noqa: E501
        :rtype: datetime
        """
        return self._finish_date

    @finish_date.setter
    def finish_date(self, finish_date):
        """Sets the finish_date of this GenericTaskWithUrl.

        The timestamp of when processing of this task finished  # noqa: E501

        :param finish_date: The finish_date of this GenericTaskWithUrl.  # noqa: E501
        :type: datetime
        """

        self._finish_date = finish_date

    @property
    def state(self):
        """Gets the state of this GenericTaskWithUrl.  # noqa: E501

        The current processing state of this task  # noqa: E501

        :return: The state of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this GenericTaskWithUrl.

        The current processing state of this task  # noqa: E501

        :param state: The state of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and state is None:  # noqa: E501
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501
        allowed_values = ["pending", "executing", "succeeded", "failed"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and state not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def failures(self):
        """Gets the failures of this GenericTaskWithUrl.  # noqa: E501

        Schemaless. If any errors occured during processing, these will be contained here.  # noqa: E501

        :return: The failures of this GenericTaskWithUrl.  # noqa: E501
        :rtype: list[object]
        """
        return self._failures

    @failures.setter
    def failures(self, failures):
        """Sets the failures of this GenericTaskWithUrl.

        Schemaless. If any errors occured during processing, these will be contained here.  # noqa: E501

        :param failures: The failures of this GenericTaskWithUrl.  # noqa: E501
        :type: list[object]
        """

        self._failures = failures

    @property
    def task_id(self):
        """Gets the task_id of this GenericTaskWithUrl.  # noqa: E501

        The unique ID of this task  # noqa: E501

        :return: The task_id of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this GenericTaskWithUrl.

        The unique ID of this task  # noqa: E501

        :param task_id: The task_id of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and task_id is None:  # noqa: E501
            raise ValueError("Invalid value for `task_id`, must not be `None`")  # noqa: E501

        self._task_id = task_id

    @property
    def parent_id(self):
        """Gets the parent_id of this GenericTaskWithUrl.  # noqa: E501

        The parents unique taskId, if any parent exists  # noqa: E501

        :return: The parent_id of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this GenericTaskWithUrl.

        The parents unique taskId, if any parent exists  # noqa: E501

        :param parent_id: The parent_id of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def task_type(self):
        """Gets the task_type of this GenericTaskWithUrl.  # noqa: E501

        The identifier string for the type of task  # noqa: E501

        :return: The task_type of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._task_type

    @task_type.setter
    def task_type(self, task_type):
        """Sets the task_type of this GenericTaskWithUrl.

        The identifier string for the type of task  # noqa: E501

        :param task_type: The task_type of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and task_type is None:  # noqa: E501
            raise ValueError("Invalid value for `task_type`, must not be `None`")  # noqa: E501

        self._task_type = task_type

    @property
    def data(self):
        """Gets the data of this GenericTaskWithUrl.  # noqa: E501

        Schemaless. Contains the payload of the task given during task creation.  # noqa: E501

        :return: The data of this GenericTaskWithUrl.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GenericTaskWithUrl.

        Schemaless. Contains the payload of the task given during task creation.  # noqa: E501

        :param data: The data of this GenericTaskWithUrl.  # noqa: E501
        :type: object
        """

        self._data = data

    @property
    def result(self):
        """Gets the result of this GenericTaskWithUrl.  # noqa: E501

        Schemaless. Contains the processing result for this task. Type is dependent on task type.  # noqa: E501

        :return: The result of this GenericTaskWithUrl.  # noqa: E501
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this GenericTaskWithUrl.

        Schemaless. Contains the processing result for this task. Type is dependent on task type.  # noqa: E501

        :param result: The result of this GenericTaskWithUrl.  # noqa: E501
        :type: object
        """

        self._result = result

    @property
    def failure_code(self):
        """Gets the failure_code of this GenericTaskWithUrl.  # noqa: E501

        If any error occured the error code for this error will be contained here.  # noqa: E501

        :return: The failure_code of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._failure_code

    @failure_code.setter
    def failure_code(self, failure_code):
        """Sets the failure_code of this GenericTaskWithUrl.

        If any error occured the error code for this error will be contained here.  # noqa: E501

        :param failure_code: The failure_code of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """

        self._failure_code = failure_code

    @property
    def url(self):
        """Gets the url of this GenericTaskWithUrl.  # noqa: E501

        The URL of the task  # noqa: E501

        :return: The url of this GenericTaskWithUrl.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this GenericTaskWithUrl.

        The URL of the task  # noqa: E501

        :param url: The url of this GenericTaskWithUrl.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and url is None:  # noqa: E501
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GenericTaskWithUrl):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GenericTaskWithUrl):
            return True

        return self.to_dict() != other.to_dict()
