# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6759
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pricemonitor_api_client.configuration import Configuration


class PostProductsRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'products': 'list[PostProduct]',
        'version': 'str',
        'identifying_attributes': 'list[PostProductsIdentifyingAttribute]'
    }

    attribute_map = {
        'products': 'products',
        'version': 'version',
        'identifying_attributes': 'identifyingAttributes'
    }

    def __init__(self, products=None, version=None, identifying_attributes=None, local_vars_configuration=None):  # noqa: E501
        """PostProductsRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._products = None
        self._version = None
        self._identifying_attributes = None
        self.discriminator = None

        self.products = products
        self.version = version
        self.identifying_attributes = identifying_attributes

    @property
    def products(self):
        """Gets the products of this PostProductsRequest.  # noqa: E501

        Products which should be added to the pricemonitor  # noqa: E501

        :return: The products of this PostProductsRequest.  # noqa: E501
        :rtype: list[PostProduct]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this PostProductsRequest.

        Products which should be added to the pricemonitor  # noqa: E501

        :param products: The products of this PostProductsRequest.  # noqa: E501
        :type: list[PostProduct]
        """
        if self.local_vars_configuration.client_side_validation and products is None:  # noqa: E501
            raise ValueError("Invalid value for `products`, must not be `None`")  # noqa: E501

        self._products = products

    @property
    def version(self):
        """Gets the version of this PostProductsRequest.  # noqa: E501

        Version of the request body. Only version 2 is supported.  # noqa: E501

        :return: The version of this PostProductsRequest.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PostProductsRequest.

        Version of the request body. Only version 2 is supported.  # noqa: E501

        :param version: The version of this PostProductsRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and version is None:  # noqa: E501
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501
        allowed_values = ["2"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and version not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `version` ({0}), must be one of {1}"  # noqa: E501
                .format(version, allowed_values)
            )

        self._version = version

    @property
    def identifying_attributes(self):
        """Gets the identifying_attributes of this PostProductsRequest.  # noqa: E501

        Non-empty list of product attributes which identify your products uniquely  # noqa: E501

        :return: The identifying_attributes of this PostProductsRequest.  # noqa: E501
        :rtype: list[PostProductsIdentifyingAttribute]
        """
        return self._identifying_attributes

    @identifying_attributes.setter
    def identifying_attributes(self, identifying_attributes):
        """Sets the identifying_attributes of this PostProductsRequest.

        Non-empty list of product attributes which identify your products uniquely  # noqa: E501

        :param identifying_attributes: The identifying_attributes of this PostProductsRequest.  # noqa: E501
        :type: list[PostProductsIdentifyingAttribute]
        """
        if self.local_vars_configuration.client_side_validation and identifying_attributes is None:  # noqa: E501
            raise ValueError("Invalid value for `identifying_attributes`, must not be `None`")  # noqa: E501

        self._identifying_attributes = identifying_attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostProductsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PostProductsRequest):
            return True

        return self.to_dict() != other.to_dict()
