export * from './account.service';
import { AccountService } from './account.service';
export * from './amazonIntegration.service';
import { AmazonIntegrationService } from './amazonIntegration.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './controlpanel.service';
import { ControlpanelService } from './controlpanel.service';
export * from './deprecated.service';
import { DeprecatedService } from './deprecated.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './feeds.service';
import { FeedsService } from './feeds.service';
export * from './internal.service';
import { InternalService } from './internal.service';
export * from './logs.service';
import { LogsService } from './logs.service';
export * from './looker.service';
import { LookerService } from './looker.service';
export * from './monitoringSchedules.service';
import { MonitoringSchedulesService } from './monitoringSchedules.service';
export * from './offers.service';
import { OffersService } from './offers.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './pluginregistration.service';
import { PluginregistrationService } from './pluginregistration.service';
export * from './preprocessing.service';
import { PreprocessingService } from './preprocessing.service';
export * from './pricerecommendations.service';
import { PricerecommendationsService } from './pricerecommendations.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './scenariostrategy.service';
import { ScenariostrategyService } from './scenariostrategy.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './strategy.service';
import { StrategyService } from './strategy.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './undocumented.service';
import { UndocumentedService } from './undocumented.service';
export * from './vendorShopMapping.service';
import { VendorShopMappingService } from './vendorShopMapping.service';
export const APIS = [AccountService, AmazonIntegrationService, CompaniesService, ControlpanelService, DeprecatedService, DomainsService, FeedsService, InternalService, LogsService, LookerService, MonitoringSchedulesService, OffersService, OrdersService, PluginregistrationService, PreprocessingService, PricerecommendationsService, ProductsService, ScenariostrategyService, SettingsService, StrategyService, TasksService, UndocumentedService, VendorShopMappingService];
