/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7012
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import java.time.OffsetDateTime
import com.patagona.pricemonitor.client.core.ApiModel

  /**
   * A contract used for data representation in the admin-endpoint
   */
case class AdminContractV2(
  /* The date and time the contract expires */
  expirationDate: Option[OffsetDateTime] = None,
  /* The contract's description */
  description: String,
  /* The id of the contract */
  id: String,
  /* The date and time the contract was created */
  creationDate: OffsetDateTime,
  `type`: ContractType,
  /* The contract-status */
  active: Boolean
) extends ApiModel


