/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6031
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import com.patagona.pricemonitor.client.core.ApiModel

case class CallbacksPricemonitorCompleted(
  bodyTemplate: Option[String] = None,
  headers: Option[Map[String, String]] = None,
  method: Option[String] = None,
  name: Option[String] = None,
  url: Option[String] = None
) extends ApiModel


