/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6758
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import java.time.OffsetDateTime
import com.patagona.pricemonitor.client.core.ApiModel

case class ComPatagonaPricemonitorShareApiDeleteOrdersByQueryRequestV3Orders(
  /* Unique identifier of the order */
  orderId: String,
  /* Creation date of the corresponding order. It is a Timestamp in UTC time zone */
  creationDate: OffsetDateTime
) extends ApiModel


