/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6075
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import java.time.OffsetDateTime
import com.patagona.pricemonitor.client.core.ApiModel

  /**
   * An offer by a specific vendor for a certain product
   */
case class GetOffersResponseOffers(
  approved: Option[Boolean] = None,
  attributes: Option[Seq[GetOffersResponseAttributes]] = None,
  availability: Option[Any] = None,
  creationDate: Option[OffsetDateTime] = None,
  deliveryCosts: Option[Double] = None,
  domain: Option[String] = None,
  maxDeliveryTime: Option[Any] = None,
  minDeliveryTime: Option[Any] = None,
  price: Option[Double] = None,
  productName: Option[String] = None,
  url: Option[String] = None,
  vendor: Option[String] = None,
  vendorIdOnDomain: Option[String] = None
) extends ApiModel


