/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5887
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import com.patagona.pricemonitor.client.core.ApiModel

  /**
   * Request body containing bulked orders
   */
case class PostCustomerOrdersRequestV2(
  /* Orders in bulk */
  orders: Seq[CustomerOrderV2],
  /* Version of orders */
  version: String
) extends ApiModel


