/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7021
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import com.patagona.pricemonitor.client.core.ApiModel

  /**
   * Request body which contains the strategy and relevant metadata
   */
case class PostScenarioStrategyRequest(
  /* Title of the scenario strategy. Should not be empty and a maximum of 50 chars is allowed */
  title: String,
  /* Description of the scenario strategy. Maximum of 1000 chars allowed */
  description: Option[String] = None,
  /* Version of the schema the scenario strategy is encoded in */
  schemaVersion: Int,
  /* This is a placeholder for a pricing strategy. These are using advanced features and are not covered by openapi. If you need to work with pricing strategies please contract us. */
  strategy: Any
) extends ApiModel


