/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts, and more.  This API supports both public endpoints for customer integration and internal endpoints for platform management. All endpoints are authenticated using either Basic Authentication or JWT Bearer tokens.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7248
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import com.patagona.pricemonitor.client.core.ApiModel

  /**
   * The detailed result of the price calculation. Exactly one of the results will be defined. This class exists only in this shape to be able to generate the correct JSON schema. Ideally, we get rid of it in future and solely rely on a sealed trait for the price recommendation results. Or we differentiate between internal and external representation.
   */
case class PriceCalculationResult(
  competitivePricingRecommendationResult: Option[ComPatagonaPricemonitorShareApiPriceCalculationResultCompetitivePricingRecommendationResult] = None,
  noPriceCalculated: Option[ComPatagonaPricemonitorShareApiPriceCalculationResultNoPriceCalculated] = None,
  formulaRecommendationResult: Option[ComPatagonaPricemonitorShareApiPriceCalculationResultFormulaRecommendationResult] = None,
  roundingPriceRecommendationResult: Option[RoundingPriceRecommendationResult] = None,
  priceCalculationFailure: Option[ComPatagonaPricemonitorShareApiPriceCalculationResultPriceCalculationFailure] = None
) extends ApiModel


