/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6251
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import com.patagona.pricemonitor.client.core.ApiModel

case class ProductOfferStatistics(
  /* The internal product id of the pricemonitor */
  productId: Option[String] = None,
  /* The offer statistics are grouped by domain. */
  statsByDomain: Option[Map[String, OfferStatistics]] = None
) extends ApiModel


