/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6627
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.patagona.pricemonitor.client.model

import java.time.OffsetDateTime
import com.patagona.pricemonitor.client.core.ApiModel

case class ScenarioStrategyResponseData(
  /* Id of the scenario strategy. */
  id: Option[Int] = None,
  /* Title of the scenario strategy. Should not be empty and a maximum of 50 chars is allowed */
  title: Option[String] = None,
  /* Description of the scenario strategy. Maximum of 1000 chars allowed */
  description: Option[String] = None,
  /* Version of the schema the scenario strategy is encoded in */
  schemaVersion: Option[Int] = None,
  /* This is a placeholder for a pricing strategy. These are using advanced features and are not covered by openapi. If you need to work with pricing strategies please contract us. */
  strategy: Option[Any] = None,
  /* Timestamp of creating the strategy scenario */
  creationDate: Option[OffsetDateTime] = None,
  /* Email address of the user who created the strategy scenario */
  createdBy: Option[String] = None,
  /* Timestamp of the last update operation */
  updateDate: Option[OffsetDateTime] = None,
  /* Email address of the user who last updated the strategy scenario */
  updatedBy: Option[String] = None
) extends ApiModel


