# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6641
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.post_scenario_strategy_request import PostScenarioStrategyRequest  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestPostScenarioStrategyRequest(unittest.TestCase):
    """PostScenarioStrategyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PostScenarioStrategyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.post_scenario_strategy_request.PostScenarioStrategyRequest()  # noqa: E501
        if include_optional :
            return PostScenarioStrategyRequest(
                title = '0', 
                description = '0', 
                schema_version = 56, 
                strategy = None
            )
        else :
            return PostScenarioStrategyRequest(
                title = '0',
                schema_version = 56,
                strategy = None,
        )

    def testPostScenarioStrategyRequest(self):
        """Test PostScenarioStrategyRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
