# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6294
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_monitoring_schedule_v3 import ComPatagonaPricemonitorShareApiMonitoringScheduleV3  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestComPatagonaPricemonitorShareApiMonitoringScheduleV3(unittest.TestCase):
    """ComPatagonaPricemonitorShareApiMonitoringScheduleV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComPatagonaPricemonitorShareApiMonitoringScheduleV3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_monitoring_schedule_v3.ComPatagonaPricemonitorShareApiMonitoringScheduleV3()  # noqa: E501
        if include_optional :
            return ComPatagonaPricemonitorShareApiMonitoringScheduleV3(
                product_query = {"regex":{"field":"field","pattern":"pattern"},"oneOf":{"field":"field","values":["values","values"]},"or":[null,null],"const":true,"in":{"field":"field"},"and":[null,null],"lt":{"field":"field","value":"value"},"eq":{"field":"field","value":"value"},"gt":{"field":"field","value":"value"}}, 
                quota = 1.337, 
                unfulfilled_only = True, 
                id = 1.337, 
                schedule = '0', 
                scheduler_job_id = '0'
            )
        else :
            return ComPatagonaPricemonitorShareApiMonitoringScheduleV3(
                quota = 1.337,
                unfulfilled_only = True,
                id = 1.337,
                schedule = '0',
                scheduler_job_id = '0',
        )

    def testComPatagonaPricemonitorShareApiMonitoringScheduleV3(self):
        """Test ComPatagonaPricemonitorShareApiMonitoringScheduleV3"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
