# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7031
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.delete_products_api_response import DeleteProductsApiResponse  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestDeleteProductsApiResponse(unittest.TestCase):
    """DeleteProductsApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DeleteProductsApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.delete_products_api_response.DeleteProductsApiResponse()  # noqa: E501
        if include_optional :
            return DeleteProductsApiResponse(
                data = pricemonitor_api_client.models.delete_products_api_response_data.DeleteProductsApiResponse_data(
                    deleted = 56, )
            )
        else :
            return DeleteProductsApiResponse(
        )

    def testDeleteProductsApiResponse(self):
        """Test DeleteProductsApiResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
