# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7132
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.plugin_registration import PluginRegistration  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestPluginRegistration(unittest.TestCase):
    """PluginRegistration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PluginRegistration
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.plugin_registration.PluginRegistration()  # noqa: E501
        if include_optional :
            return PluginRegistration(
                plugin_id = '0', 
                shop_system = '0', 
                metrics_url = '0'
            )
        else :
            return PluginRegistration(
        )

    def testPluginRegistration(self):
        """Test PluginRegistration"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
