# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6667
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_customer_contract_settings import ComPatagonaPricemonitorShareApiCustomerContractSettings  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestComPatagonaPricemonitorShareApiCustomerContractSettings(unittest.TestCase):
    """ComPatagonaPricemonitorShareApiCustomerContractSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComPatagonaPricemonitorShareApiCustomerContractSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_customer_contract_settings.ComPatagonaPricemonitorShareApiCustomerContractSettings()  # noqa: E501
        if include_optional :
            return ComPatagonaPricemonitorShareApiCustomerContractSettings(
                include_delivery_costs = True, 
                domains = [
                    '0'
                    ], 
                dynamic_monitoring = {"threshold":6.027456183070403,"analysisRange":0,"adjustedInterval":1}, 
                currency = 'EUR', 
                image_url_tag = '0', 
                callbacks = {"pricemonitorCompleted":[{"headers":{"key":"headers"},"method":"method","bodyTemplate":"bodyTemplate","name":"name","url":"url"},{"headers":{"key":"headers"},"method":"method","bodyTemplate":"bodyTemplate","name":"name","url":"url"}]}, 
                msrp_tag = '0', 
                map_tag = '0'
            )
        else :
            return ComPatagonaPricemonitorShareApiCustomerContractSettings(
                include_delivery_costs = True,
                domains = [
                    '0'
                    ],
        )

    def testComPatagonaPricemonitorShareApiCustomerContractSettings(self):
        """Test ComPatagonaPricemonitorShareApiCustomerContractSettings"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
