# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6694
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.query_price_dumping_stats_api_response import QueryPriceDumpingStatsApiResponse  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestQueryPriceDumpingStatsApiResponse(unittest.TestCase):
    """QueryPriceDumpingStatsApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test QueryPriceDumpingStatsApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.query_price_dumping_stats_api_response.QueryPriceDumpingStatsApiResponse()  # noqa: E501
        if include_optional :
            return QueryPriceDumpingStatsApiResponse(
                data = {"statsOverAllomains":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5},"statsPerDomain":[{"domain":"domain","productPriceDumpingStats":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5}},{"domain":"domain","productPriceDumpingStats":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5}}]}
            )
        else :
            return QueryPriceDumpingStatsApiResponse(
                data = {"statsOverAllomains":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5},"statsPerDomain":[{"domain":"domain","productPriceDumpingStats":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5}},{"domain":"domain","productPriceDumpingStats":{"potentiallyInitiatedPriceDumpings":5,"uniqueProductInitiatedPriceDumpings":6,"productsAtMinPrice":0,"uniqueProductPotentiallyInitiatedPriceDumpings":1,"initiatedPriceDumpings":5}}]},
        )

    def testQueryPriceDumpingStatsApiResponse(self):
        """Test QueryPriceDumpingStatsApiResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
