# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7137
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.query_offers_api_response import QueryOffersApiResponse  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestQueryOffersApiResponse(unittest.TestCase):
    """QueryOffersApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test QueryOffersApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.query_offers_api_response.QueryOffersApiResponse()  # noqa: E501
        if include_optional :
            return QueryOffersApiResponse(
                data = [
                    pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/api_offer.com.patagona.pricemonitor.share.api.ApiOffer(
                        position_by_total_price = 56, 
                        delivery_costs = 1.337, 
                        max_delivery_time = 56, 
                        url = '0', 
                        vendor_domain_id = '0', 
                        domain = '0', 
                        price = 1.337, 
                        min_delivery_time = 56, 
                        gtin = 1.337, 
                        position_by_unit_price = 56, 
                        availability = True, 
                        attributes = [
                            pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/offer_attribute.com.patagona.pricemonitor.share.api.OfferAttribute(
                                name = '0', 
                                value = '0', )
                            ], 
                        vendor_name = '0', 
                        retrieval_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        product_name = '0', 
                        currency = '0', 
                        product_id = '0', 
                        ignored = True, )
                    ]
            )
        else :
            return QueryOffersApiResponse(
                data = [
                    pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/api_offer.com.patagona.pricemonitor.share.api.ApiOffer(
                        position_by_total_price = 56, 
                        delivery_costs = 1.337, 
                        max_delivery_time = 56, 
                        url = '0', 
                        vendor_domain_id = '0', 
                        domain = '0', 
                        price = 1.337, 
                        min_delivery_time = 56, 
                        gtin = 1.337, 
                        position_by_unit_price = 56, 
                        availability = True, 
                        attributes = [
                            pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/offer_attribute.com.patagona.pricemonitor.share.api.OfferAttribute(
                                name = '0', 
                                value = '0', )
                            ], 
                        vendor_name = '0', 
                        retrieval_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        product_name = '0', 
                        currency = '0', 
                        product_id = '0', 
                        ignored = True, )
                    ],
        )

    def testQueryOffersApiResponse(self):
        """Test QueryOffersApiResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
