# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7020
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.price_recommendation_api_query_v2 import PriceRecommendationApiQueryV2  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestPriceRecommendationApiQueryV2(unittest.TestCase):
    """PriceRecommendationApiQueryV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PriceRecommendationApiQueryV2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.price_recommendation_api_query_v2.PriceRecommendationApiQueryV2()  # noqa: E501
        if include_optional :
            return PriceRecommendationApiQueryV2(
                filter = None, 
                pagination = pricemonitor_api_client.models.pagination.Pagination(
                    limit = 56, 
                    start = 56, ), 
                range = pricemonitor_api_client.models.time_range.TimeRange(
                    end = '2018-04-06T13:46:13Z', 
                    start = '2018-04-04T13:46:13Z', ), 
                sort = pricemonitor_api_client.models.price_recommendation_query_sort_order_v2.PriceRecommendationQuerySortOrderV2(
                    metric = 'productId', 
                    order = 'asc', )
            )
        else :
            return PriceRecommendationApiQueryV2(
                pagination = pricemonitor_api_client.models.pagination.Pagination(
                    limit = 56, 
                    start = 56, ),
                range = pricemonitor_api_client.models.time_range.TimeRange(
                    end = '2018-04-06T13:46:13Z', 
                    start = '2018-04-04T13:46:13Z', ),
        )

    def testPriceRecommendationApiQueryV2(self):
        """Test PriceRecommendationApiQueryV2"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
