# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts, and more.  This API supports both public endpoints for customer integration and internal endpoints for platform management. All endpoints are authenticated using either Basic Authentication or JWT Bearer tokens.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7235
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pricemonitor_api_client
from pricemonitor_api_client.api.offers_api import OffersApi  # noqa: E501
from pricemonitor_api_client.rest import ApiException


class TestOffersApi(unittest.TestCase):
    """OffersApi unit test stubs"""

    def setUp(self):
        self.api = pricemonitor_api_client.api.offers_api.OffersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_cheapest_vendors_manufacturer_v2(self):
        """Test case for get_cheapest_vendors_manufacturer_v2

        Query cheapest offers  # noqa: E501
        """
        pass

    def test_get_complex_offer_filters_vendor_v2(self):
        """Test case for get_complex_offer_filters_vendor_v2

        Get all complex filters for the given contract.  # noqa: E501
        """
        pass

    def test_get_offer_filters_vendor_v2(self):
        """Test case for get_offer_filters_vendor_v2

        Get all vendor filters for contract  # noqa: E501
        """
        pass

    def test_get_offer_statistics_manufacturer_v3(self):
        """Test case for get_offer_statistics_manufacturer_v3

        Get offer statistics per product of a contract  # noqa: E501
        """
        pass

    def test_get_offers(self):
        """Test case for get_offers

        Get all offers for all products  # noqa: E501
        """
        pass

    def test_get_offers_manufacturer_v3(self):
        """Test case for get_offers_manufacturer_v3

        Get offers for time range  # noqa: E501
        """
        pass

    def test_get_offers_shops_manufacturer_v3(self):
        """Test case for get_offers_shops_manufacturer_v3

        Get shops with offers for time range  # noqa: E501
        """
        pass

    def test_get_offers_shops_vendor_v3(self):
        """Test case for get_offers_shops_vendor_v3

        Get shops with offers for time range per domain  # noqa: E501
        """
        pass

    def test_get_offers_vendor_v3(self):
        """Test case for get_offers_vendor_v3

        Get offers for timerange  # noqa: E501
        """
        pass

    def test_get_price_cutters_manufacturer_v2(self):
        """Test case for get_price_cutters_manufacturer_v2

        Query price cutters [manufacturer]  # noqa: E501
        """
        pass

    def test_get_price_cutters_vendor_v2(self):
        """Test case for get_price_cutters_vendor_v2

        Query price cutters [vendor]  # noqa: E501
        """
        pass

    def test_get_product_filters_by_id_vendor_v2(self):
        """Test case for get_product_filters_by_id_vendor_v2

        Get filtered offers  # noqa: E501
        """
        pass

    def test_get_product_filters_by_range_vendor_v2(self):
        """Test case for get_product_filters_by_range_vendor_v2

        Get all the filters product-wise for the given contract.  # noqa: E501
        """
        pass

    def test_get_product_metrics_by_contract(self):
        """Test case for get_product_metrics_by_contract

        Get product metrics for contract  # noqa: E501
        """
        pass

    def test_get_product_price_violations_manufacturer_v2(self):
        """Test case for get_product_price_violations_manufacturer_v2

        Get product price violations [manufacturer]  # noqa: E501
        """
        pass

    def test_get_product_price_violations_vendor_v2(self):
        """Test case for get_product_price_violations_vendor_v2

        Get product price violations [vendor]  # noqa: E501
        """
        pass

    def test_get_vendors_by_domain_manufacturer_v2(self):
        """Test case for get_vendors_by_domain_manufacturer_v2

        Get vendors by domain  # noqa: E501
        """
        pass

    def test_position_distribution(self):
        """Test case for position_distribution

        Update position distribution  # noqa: E501
        """
        pass

    def test_post_offers_in_a_bulk_vendor_v2(self):
        """Test case for post_offers_in_a_bulk_vendor_v2

        Add offers in bulk  # noqa: E501
        """
        pass

    def test_prices_by_day_by_product_id_manufacturer_v2(self):
        """Test case for prices_by_day_by_product_id_manufacturer_v2

        Query prices by day by product  # noqa: E501
        """
        pass

    def test_put_complex_offer_filters_vendor_v2(self):
        """Test case for put_complex_offer_filters_vendor_v2

        Add the complex filters for the given contract.  # noqa: E501
        """
        pass

    def test_put_offer_filters_vendor_v2(self):
        """Test case for put_offer_filters_vendor_v2

        Store vendor filters for contract  # noqa: E501
        """
        pass

    def test_query_offers_manufacturer_v3(self):
        """Test case for query_offers_manufacturer_v3

        Query offers [manufacturer]  # noqa: E501
        """
        pass

    def test_query_offers_stats_manufacturer_v31(self):
        """Test case for query_offers_stats_manufacturer_v31

        Query offer statistics per product  # noqa: E501
        """
        pass

    def test_query_offers_stats_vendor_v31(self):
        """Test case for query_offers_stats_vendor_v31

        Query offer statistics per product  # noqa: E501
        """
        pass

    def test_query_offers_vendor_v3(self):
        """Test case for query_offers_vendor_v3

        Query offers [vendor]  # noqa: E501
        """
        pass

    def test_raw_offers(self):
        """Test case for raw_offers

        Get offers for contract  # noqa: E501
        """
        pass

    def test_segment_offers_manufacturer_v2(self):
        """Test case for segment_offers_manufacturer_v2

        Update segment offers [manufacturer]  # noqa: E501
        """
        pass

    def test_segment_offers_vendor_v2(self):
        """Test case for segment_offers_vendor_v2

        Update segment offers [vendor]  # noqa: E501
        """
        pass

    def test_stats_manufacturer_v2(self):
        """Test case for stats_manufacturer_v2

        Get contract statistics [manufacturer]  # noqa: E501
        """
        pass

    def test_timestamps_manufacturer_v2(self):
        """Test case for timestamps_manufacturer_v2

        Get timestamps  # noqa: E501
        """
        pass

    def test_validate_offers_manufacturer_v2(self):
        """Test case for validate_offers_manufacturer_v2

        Validate offers [manufacturer]  # noqa: E501
        """
        pass

    def test_validate_offers_vendor_v2(self):
        """Test case for validate_offers_vendor_v2

        Validate offers [vendor]  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
