# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7059
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.get_manufacturer_v3_api_response import GetManufacturerV3ApiResponse  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestGetManufacturerV3ApiResponse(unittest.TestCase):
    """GetManufacturerV3ApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetManufacturerV3ApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.get_manufacturer_v3_api_response.GetManufacturerV3ApiResponse()  # noqa: E501
        if include_optional :
            return GetManufacturerV3ApiResponse(
                data = pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/get_contract_response_v3.com.patagona.pricemonitor.share.api.GetContractResponseV3(
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '0', 
                    contract_type = 'Pricemonitor for manufacturers', 
                    creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sid = '0', 
                    company_id = 1.337, 
                    active = True, )
            )
        else :
            return GetManufacturerV3ApiResponse(
                data = pricemonitor_api_client.models.com/patagona/pricemonitor/share/api/get_contract_response_v3.com.patagona.pricemonitor.share.api.GetContractResponseV3(
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    description = '0', 
                    contract_type = 'Pricemonitor for manufacturers', 
                    creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sid = '0', 
                    company_id = 1.337, 
                    active = True, ),
        )

    def testGetManufacturerV3ApiResponse(self):
        """Test GetManufacturerV3ApiResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
