# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts, and more.  This API supports both public endpoints for customer integration and internal endpoints for platform management. All endpoints are authenticated using either Basic Authentication or JWT Bearer tokens.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.7190
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pricemonitor_api_client
from pricemonitor_api_client.api.account_api import AccountApi  # noqa: E501
from pricemonitor_api_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = pricemonitor_api_client.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate(self):
        """Test case for authenticate

        Authenticate  # noqa: E501
        """
        pass

    def test_change_password(self):
        """Test case for change_password

        Change password  # noqa: E501
        """
        pass

    def test_check_user_confirmation(self):
        """Test case for check_user_confirmation

        Check if a specific confirmation token exists  # noqa: E501
        """
        pass

    def test_confirm_user(self):
        """Test case for confirm_user

        Confirm an unconfirmed user  # noqa: E501
        """
        pass

    def test_delete_user_role(self):
        """Test case for delete_user_role

        Delete user role  # noqa: E501
        """
        pass

    def test_generate_account_password_v3(self):
        """Test case for generate_account_password_v3

        Generate password for user account  # noqa: E501
        """
        pass

    def test_login_by_auth_token(self):
        """Test case for login_by_auth_token

        Log in with authentication token  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        Log out  # noqa: E501
        """
        pass

    def test_post_account_v3(self):
        """Test case for post_account_v3

        Create user account  # noqa: E501
        """
        pass

    def test_request_new_password(self):
        """Test case for request_new_password

        Request a new password  # noqa: E501
        """
        pass

    def test_reset_password(self):
        """Test case for reset_password

        Reset the password  # noqa: E501
        """
        pass

    def test_update_user_role(self):
        """Test case for update_user_role

        Add user role  # noqa: E501
        """
        pass

    def test_user_info(self):
        """Test case for user_info

        Details of the current user  # noqa: E501
        """
        pass

    def test_user_signup(self):
        """Test case for user_signup

        Create a new user account in the system  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
