# coding: utf-8

"""
    Pricemonitor API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6572
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pricemonitor_api_client
from pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_api_product_v3 import ComPatagonaPricemonitorShareApiApiProductV3  # noqa: E501
from pricemonitor_api_client.rest import ApiException

class TestComPatagonaPricemonitorShareApiApiProductV3(unittest.TestCase):
    """ComPatagonaPricemonitorShareApiApiProductV3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComPatagonaPricemonitorShareApiApiProductV3
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pricemonitor_api_client.models.com_patagona_pricemonitor_share_api_api_product_v3.ComPatagonaPricemonitorShareApiApiProductV3()  # noqa: E501
        if include_optional :
            return ComPatagonaPricemonitorShareApiApiProductV3(
                name = '0', 
                tags = [
                    {"stringValue":"stringValue","integerValue":5,"booleanValue":true,"doubleValue":5.962133916683182,"label":"label"}
                    ], 
                min_price_boundary = 1.337, 
                gtin = 1.337, 
                customer_product_id = '0', 
                id = '0', 
                max_price_boundary = 1.337, 
                reference_price = 1.337
            )
        else :
            return ComPatagonaPricemonitorShareApiApiProductV3(
                name = '0',
                tags = [
                    {"stringValue":"stringValue","integerValue":5,"booleanValue":true,"doubleValue":5.962133916683182,"label":"label"}
                    ],
                id = '0',
                reference_price = 1.337,
        )

    def testComPatagonaPricemonitorShareApiApiProductV3(self):
        """Test ComPatagonaPricemonitorShareApiApiProductV3"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
