# coding: utf-8

"""
    Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.6998
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pricemonitor_api_client
from pricemonitor_api_client.api.domains_api import DomainsApi  # noqa: E501
from pricemonitor_api_client.rest import ApiException


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self):
        self.api = pricemonitor_api_client.api.domains_api.DomainsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_domains_v2(self):
        """Test case for get_all_domains_v2

        Gets a list of all available domains (V2)  # noqa: E501
        """
        pass

    def test_get_all_domains_v3(self):
        """Test case for get_all_domains_v3

        Get a list of all available domains (V3)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
