/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6970
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferAttribute } from './offerAttribute';


export interface ApiOffer { 
    attributes?: Array<OfferAttribute>;
    availability?: boolean;
    creationDate: string;
    contractId: string;
    currency: string;
    deliveryCosts: number;
    domain: string;
    gtin?: number;
    ignored: boolean;
    maxDeliveryTime?: number;
    minDeliveryTime?: number;
    positionByUnitPrice?: number;
    positionByTotalPrice?: number;
    price: number;
    productId: string;
    productName: string;
    retrievalDate?: string;
    url: string;
    vendorDomainId?: string;
    vendorName: string;
}

