/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6917
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShopRank } from './shopRank';


export interface OfferStatistics { 
    /**
     * The average price of the offers, always be provided with two decimal places
     */
    averagePrice: number;
    /**
     * The lowest price of the offers, always be provided with two decimal places
     */
    minPrice: number;
    /**
     * The number of the found offers
     */
    offerCount: number;
    ownPosition?: ShopRank;
}

