/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts, and more.  This API supports both public endpoints for customer integration and internal endpoints for platform management. All endpoints are authenticated using either Basic Authentication or JWT Bearer tokens.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7243
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeRange } from './timeRange';
import { ProductsFilter } from './productsFilter';


export interface PostOfferStatisticsRequest { 
    filter: ProductsFilter;
    includeDeliveryCosts: boolean;
    /**
     * Providing own shops names enables calculating shop positions. The keys are domain names. The values are lists of shop names.
     */
    ownShopNames: { [key: string]: Array<string>; };
    range: TimeRange;
}

