/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6395
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Shows if product belongs to Amazon Buybox
 */
export interface PricemonitorAmazonBuyboxProductStatsV3 { 
    /**
     * Internal product identifier
     */
    productId: number;
    /**
     * Indicates if product is Amazon Prime product and is in Amazon Buybox
     */
    isInPrimeBuybox: boolean;
    /**
     * Indicates if product is in Amazon Buybox
     */
    isInNonPrimeBuybox: boolean;
}

