/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6952
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorCustomerOrderProductMappingV2 } from './pricemonitorCustomerOrderProductMappingV2';
import { PricemonitorCustomerOrderItemV2 } from './pricemonitorCustomerOrderItemV2';


/**
 * An order placed in a shop.
 */
export interface PricemonitorCustomerOrderV2 { 
    /**
     * Shipping costs of the order
     */
    shippingCosts: number;
    /**
     * Unique id of an order. It must mean unique in the shop, not in the pricemonitor.
     */
    orderId: string;
    /**
     * List of bought items
     */
    items: Array<PricemonitorCustomerOrderItemV2>;
    /**
     * Total price of the order
     */
    totalPrice: number;
    /**
     * A relation from the products in your system to the pricemonitor. Currently it must contain exactly one element.
     */
    productMappings: Array<PricemonitorCustomerOrderProductMappingV2>;
    /**
     * Origin of an order, e.g. the online shop were the order is placed
     */
    origin: string;
    /**
     * Date when the order is created in UTC
     */
    creationDate: string;
    /**
     * Currency used in the order. ISO 4217 Currency Codes: e.g. EUR
     */
    currency: string;
    /**
     * Referrer of an order. Third party (e.g. marketplace) which referred the customer to the online shop
     */
    referrer?: string;
}

