/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6875
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the pagination details such as the start index and the number of records to fetch (limit). At maximum it\'s allowed to query 10,000 records.
 */
export interface PricemonitorPostOrderStatisticsRequestV3Pagination { 
    /**
     * 
     */
    start: number;
    /**
     * 
     */
    limit: number;
}

