/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7059
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User Information of company users.
 */
export interface PricemonitorGetCompanyUsersUser { 
    /**
     * The id of the user.
     */
    id: number;
    /**
     * The email of the user.
     */
    email: string;
    /**
     * The name of the user.
     */
    name: string;
    /**
     * The last active datetime of the user. In case the user has no activity yet, the last active datetime will be returned as \'1970-01-01T00:00:01.000Z\'.
     */
    lastActiveDate: string;
}

