/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6432
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whitelist entry for offers based on different attributes.
 */
export interface PricemonitorOfferSelector { 
    /**
     * The domain
     */
    domain: string;
    /**
     * The vendor name
     */
    vendorName: string;
    /**
     * The product name
     */
    productName: string;
}

