/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6773
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorPutItemsResponseV3 } from './pricemonitorPutItemsResponseV3';


export interface PutItemsV3ApiResponse { 
    data: PricemonitorPutItemsResponseV3;
}

