/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6459
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorActivateMarketplaceResponseV3 } from './pricemonitorActivateMarketplaceResponseV3';


export interface ActivateMarketplaceResponseV3ApiResponse { 
    data: PricemonitorActivateMarketplaceResponseV3;
}

