/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetOffersResponseAttributes } from './getOffersResponseAttributes';


/**
 * An offer by a specific vendor for a certain product
 */
export interface GetOffersResponseOffers { 
    approved?: boolean;
    attributes?: Array<GetOffersResponseAttributes>;
    availability?: object;
    creationDate?: string;
    deliveryCosts?: number;
    domain?: string;
    maxDeliveryTime?: object;
    minDeliveryTime?: object;
    price?: number;
    productName?: string;
    url?: string;
    vendor?: string;
    vendorIdOnDomain?: string;
}

