/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5425
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComPatagonaPricemonitorShareApiProductMonitoringStatus } from './comPatagonaPricemonitorShareApiProductMonitoringStatus';


export interface GetProductMonitoringStatusVendorV3ApiResponse { 
    data: Array<ComPatagonaPricemonitorShareApiProductMonitoringStatus>;
}

