/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6472
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorGetShopsByDomainResponseV3 } from './pricemonitorGetShopsByDomainResponseV3';


export interface GetShopsByDomainResponseV3ApiResponse { 
    data: Array<PricemonitorGetShopsByDomainResponseV3>;
}

