/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts, and more.  This API supports both public endpoints for customer integration and internal endpoints for platform management. All endpoints are authenticated using either Basic Authentication or JWT Bearer tokens.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7297
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The job types are fixed and defined in the scheduler code. 
 */
export type JobType = 'ShopIntegrationUpdateProductsJob' | 'ShopIntegrationStartShopSyncJob' | 'MonitoringJob' | 'PreprocessingJob' | 'ReportJob' | 'ProductImportJob' | 'PricewatchJob';

export const JobType = {
    ShopIntegrationUpdateProductsJob: 'ShopIntegrationUpdateProductsJob' as JobType,
    ShopIntegrationStartShopSyncJob: 'ShopIntegrationStartShopSyncJob' as JobType,
    MonitoringJob: 'MonitoringJob' as JobType,
    PreprocessingJob: 'PreprocessingJob' as JobType,
    ReportJob: 'ReportJob' as JobType,
    ProductImportJob: 'ProductImportJob' as JobType,
    PricewatchJob: 'PricewatchJob' as JobType
};

