/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5156
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostOrdersBulkApiResponseData } from './postOrdersBulkApiResponseData';
import { ApiError } from './apiError';


export interface PostOrdersBulkApiResponseData1 { 
    data?: PostOrdersBulkApiResponseData;
    errors?: Array<ApiError>;
}

