/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5824
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines request parameters to retrieve Amazon Buybox product stats
 */
export interface PricemonitorPostAmazonBuyboxProductsStatsRequestV3 { 
    /**
     * Defines start date for time range when to search if products are Amazon Buybox.
     */
    startDate: string;
    /**
     * Defines start date for time range when to search if products are Amazon Buybox.
     */
    endDate: string;
    /**
     * Defines a list of product ids that should checked if in Amazon Buybox. Max allowed ids is 10000 Requirements: - Max allowed product ids per request == 10000
     */
    productIds: Array<number>;
}

