/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7133
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorPriceCalculationResultPriceCalculationFailure } from './pricemonitorPriceCalculationResultPriceCalculationFailure';
import { PricemonitorPriceCalculationResultFormulaRecommendationResult } from './pricemonitorPriceCalculationResultFormulaRecommendationResult';
import { PricemonitorPriceCalculationResultNoPriceCalculated } from './pricemonitorPriceCalculationResultNoPriceCalculated';
import { PricemonitorPriceCalculationResultCompetitivePricingRecommendationResult } from './pricemonitorPriceCalculationResultCompetitivePricingRecommendationResult';
import { PricemonitorRoundingPriceRecommendationResult } from './pricemonitorRoundingPriceRecommendationResult';


/**
 * The detailed result of the price calculation. Exactly one of the results will be defined. This class exists only in this shape to be able to generate the correct JSON schema. Ideally, we get rid of it in future and solely rely on a sealed trait for the price recommendation results. Or we differentiate between internal and external representation.
 */
export interface PricemonitorPriceCalculationResult { 
    competitivePricingRecommendationResult?: PricemonitorPriceCalculationResultCompetitivePricingRecommendationResult;
    noPriceCalculated?: PricemonitorPriceCalculationResultNoPriceCalculated;
    formulaRecommendationResult?: PricemonitorPriceCalculationResultFormulaRecommendationResult;
    roundingPriceRecommendationResult?: PricemonitorRoundingPriceRecommendationResult;
    priceCalculationFailure?: PricemonitorPriceCalculationResultPriceCalculationFailure;
}

