/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5511
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PriceRecommendationQuerySortOrderV2 { 
    metric: PriceRecommendationQuerySortOrderV2.MetricEnum;
    order: PriceRecommendationQuerySortOrderV2.OrderEnum;
}
export namespace PriceRecommendationQuerySortOrderV2 {
    export type MetricEnum = 'productId' | 'RelativePriceChangePercentage';
    export const MetricEnum = {
        ProductId: 'productId' as MetricEnum,
        RelativePriceChangePercentage: 'RelativePriceChangePercentage' as MetricEnum
    };
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    };
}


