/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6021
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorContractType } from './pricemonitorContractType';


/**
 * A contract used for data representation in the admin-endpoint
 */
export interface PricemonitorAdminContractV2 { 
    /**
     * The date and time the contract expires
     */
    expirationDate?: string;
    /**
     * The contract\'s description
     */
    description: string;
    /**
     * The id of the contract
     */
    id: string;
    /**
     * The date and time the contract was created
     */
    creationDate: string;
    type: PricemonitorContractType;
    /**
     * The contract-status
     */
    active: boolean;
}

