/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6059
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This case class is used for serializing contract-information for the account-endpoints
 */
export interface PricemonitorUserContract { 
    /**
     * The contract\'s name
     */
    name: string;
    /**
     * The contract\'s id
     */
    id: number;
    type: string;
    /**
     * The contract\'s string-id
     */
    sid: string;
    /**
     * The contract status
     */
    active: boolean;
}

