/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5520
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorProductMonitoringStatusOnDomainOutcome } from './pricemonitorProductMonitoringStatusOnDomainOutcome';


/**
 * Describes the monitoring status of a product on a certain domain.
 */
export interface PricemonitorProductMonitoringStatusOnDomain { 
    /**
     * The domain which gets monitored.
     */
    domain: string;
    /**
     * The last time pricemonitor tried to monitor the product on the given domain. If this doesn\'t exist it mean\'s that pricemonitor haven\'t tried to monitor this product on the domain yet. One reason could be that the product is very new or the domain has just recently been added to the contract.
     */
    startedAt?: string;
    /**
     * The last time pricemonitor completed monitoring the product on the given domain.
     */
    completedAt?: string;
    outcome?: PricemonitorProductMonitoringStatusOnDomainOutcome;
}

