/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5509
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorContractFeatures } from './pricemonitorContractFeatures';


export interface PricemonitorGetContractSettingsResponseV1 { 
    name: string;
    expirationDate?: string;
    portals: Array<string>;
    includeDeliveryCosts: boolean;
    features: PricemonitorContractFeatures;
    imageTag?: string;
    company: string;
    id: number;
    currency: string;
    type: string;
    sid: string;
    active: boolean;
}

