/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6969
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorShopV3 } from './pricemonitorShopV3';


/**
 * Online shops can have different names per domain despite they belong to the same entity. This entity is further called \"vendor\". A vendor shop mapping represents shops which are associated to a vendor.
 */
export interface PricemonitorVendorShopMappingV3 { 
    /**
     * Unique identifier of a vendor
     */
    id: number;
    /**
     * Vendor name
     */
    vendorName: string;
    /**
     * List of shops associated with the specified vendor
     */
    shops: Array<PricemonitorShopV3>;
}

