/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6021
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorCallbacksPricemonitorCompleted } from './pricemonitorCallbacksPricemonitorCompleted';


export interface PricemonitorCallbacks { 
    pricemonitorCompleted: Array<PricemonitorCallbacksPricemonitorCompleted>;
}

