/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.7059
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A single price point of a product
 */
export interface PricemonitorPricesByDayByProductIdResponsePricePointV2 { 
    /**
     * The price
     */
    price: number;
    /**
     * The delivery costs
     */
    deliveryCosts: number;
    /**
     * The timestamp of when the price was found
     */
    timestamp: string;
}

