/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6549
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Authorization status of a seller on Amazon.
 */
export interface PricemonitorGetAuthorizationStatusResponseV3 { 
    /**
     * Whether a seller is authorized or not.
     */
    authorized: boolean;
}

