/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6746
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PricemonitorDeleteOrdersByQueryRequestV3Orders } from './pricemonitorDeleteOrdersByQueryRequestV3Orders';


/**
 * Request to delete a list of customer orders by providing an order query Notes: <br> - At maximum it\'s allowed to provide 10,000 order queries per request. <br>
 */
export interface PricemonitorDeleteOrdersByQueryRequestV3 { 
    /**
     * List of order queries, each query should include an order id and its corresponding creation date
     */
    orders: Array<PricemonitorDeleteOrdersByQueryRequestV3Orders>;
}

