/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6896
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a new contract.
 */
export interface PricemonitorCreateContractRequest { 
    /**
     * Type of the contract. Currently, only 2 types are supported: - Pricemonitor for manufacturers - Pricemonitor for resellers
     */
    contractType: string;
    /**
     * Name of the new contract
     */
    contractName: string;
    /**
     * Expiration date
     */
    expirationDate?: string;
}

