/**
 * Omnia 2.0 API The Omnia 2.0 API is RESTful and provides access to the backend of Omnia 2.0 and Pricemonitor. It is used to manage products, offers, contracts and more.
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6896
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Filter product statistics by a list of allowed internal pricemonitor product ids
 */
export interface ProductsFilter { 
    type?: ProductsFilter.TypeEnum;
    left?: object;
    right?: object;
    comparison?: ProductsFilter.ComparisonEnum;
}
export namespace ProductsFilter {
    export type TypeEnum = 'ComparisonFilter';
    export const TypeEnum = {
        ComparisonFilter: 'ComparisonFilter' as TypeEnum
    };
    export type ComparisonEnum = 'StringInSequence';
    export const ComparisonEnum = {
        StringInSequence: 'StringInSequence' as ComparisonEnum
    };
}


