/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.6620
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TimeRange { 
    /**
     * Timestamp of end of time range, formatted as ISO Date in UTC
     */
    end: string;
    /**
     * Timestamp of start of time range, formatted as ISO Date in UTC
     */
    start: string;
}

