export * from './account.service';
import { AccountService } from './account.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './feeds.service';
import { FeedsService } from './feeds.service';
export * from './logs.service';
import { LogsService } from './logs.service';
export * from './offers.service';
import { OffersService } from './offers.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './pluginregistration.service';
import { PluginregistrationService } from './pluginregistration.service';
export * from './pricerecommendations.service';
import { PricerecommendationsService } from './pricerecommendations.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export const APIS = [AccountService, CompaniesService, FeedsService, LogsService, OffersService, OrdersService, PluginregistrationService, PricerecommendationsService, ProductsService, SettingsService, TasksService];
