/**
 * Pricemonitor API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.5145
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostProduct } from './postProduct';


/**
 * Request body which contains products
 */
export interface PostProductsRequest { 
    /**
     * Non-empty list of product attributes which identify your products uniquely
     */
    identifyingAttributes?: Array<PostProductsRequest.IdentifyingAttributesEnum>;
    /**
     * Products which should be added to the pricemonitor
     */
    products?: Array<PostProduct>;
    /**
     * Version of the request body. Only version 2 is supported.
     */
    version?: PostProductsRequest.VersionEnum;
}
export namespace PostProductsRequest {
    export type IdentifyingAttributesEnum = 'customerProductId' | 'gtin' | 'name';
    export const IdentifyingAttributesEnum = {
        CustomerProductId: 'customerProductId' as IdentifyingAttributesEnum,
        Gtin: 'gtin' as IdentifyingAttributesEnum,
        Name: 'name' as IdentifyingAttributesEnum
    };
    export type VersionEnum = '2';
    export const VersionEnum = {
        _2: '2' as VersionEnum
    };
}


