name: typescript-angular build

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        angular_client_dir:
          [
            pricemonitor-internal-typescript-angular,
            pricemonitor-internal-typescript-angular-13,
          ]
        node-version: [16.x]
    defaults:
      run:
        working-directory: clients/${{ matrix.angular_client_dir }}/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        #dummy change to run github action
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com/"
      - run: npm install
      - run: npm run build
